name: fresume_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  responsive_framework: ^0.1.5
  pdf: ^3.6.5
  flutter_riverpod: ^1.0.3
  get: ^4.3.8
  freezed_annotation: ^0.14.2
  freezed: ^0.14.2
  build_runner: ^2.0.4
  intl: ^0.17.0
  pdf_render: ^1.0.19
  printing: ^5.3.0
  universal_html: ^2.0.8
  
  google_fonts: ^2.2.0
  json_serializable: ^4.1.3
  adaptive_theme: ^2.3.0
  uuid: ^3.0.4
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.10.3
  firebase_database: ^9.0.5
  flutterfire_ui: ^0.3.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true